export const ADD_URL = 'ADD CARD';
export const CHECK_NOW = 'CHECK_NOW';
export const FINISHED_URL_ADD = 'FINISHED_URL_ADD';
// CHECK STATUS ACTION
export const CHECK_STATUS_STARTED = "CHECK_STATUS_STARTED";
export const CHECK_STATUS_FINISHED = "CHECK_STATUS_FINISHED";
export const CHECK_STATUS_ERROR = "CHECK_STATUS_ERROR";
// LOAD GRAPH
export const LOAD_GRAPH_DATA = "LOAD_GRAPH_DATA";
